# name: Build & Deploy
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: copy file via ssh password
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: forestfolio.xyz
#           username: ${{secrets.SSH_USERNAME}}
#           password: ${{secrets.SSH_PASSWORD}}
#           port: 22
#           source: "."
#           target: "/var/www/html"
#           timeout: 120s

name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ForestFolio
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: 22
          script:
            mkdir test
            cd test
            git clone git@github.com:https://github.com/tmitchell1234/JJTLPContacts.git
            echo 'DEPLOYED FOREST FOLIO'
