name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ForestFolio
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: forestfolio.xyz
          key: ${{secrets.SSH_KEY}}
          username: root

          script:
            mkdir test
            cd test
            git clone git@github.com:https://github.com/tmitchell1234/JJTLPContacts.git
            echo 'DEPLOYED FOREST FOLIO'
