# name: Build & Deploy
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: copy file via ssh password
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: forestfolio.xyz
#           username: ${{secrets.SSH_USERNAME}}
#           password: ${{secrets.SSH_PASSWORD}}
#           port: 22
#           source: "."
#           target: "/var/www/html"
#           timeout: 120s

name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: html
          remote: ~/test
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
