# name: Build & Deploy
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: build
#           path: build
#       - name: Create SSH key
#         run: |
#           install -m 600 -D /dev/null ~/.ssh/id_rsa
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
#       - name: Deploy with rsync
#         run: rsync -rav --delete build/ user@host:/
