name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
     runs-on: ubuntu-latest
      steps:
        - name: Deploy ForestFolio
          uses: appleboy/ssh-action@v0.1.2
          uses: appleboy/ssh-action@v1.02
          with:
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
